import type { NewProduct } from "./db";

/**
 * Official Webor price list, effective 21 Dec 2025 (small appliances per the most
 * recent list), from Nexon Corporation Pvt. Ltd. Prices are NPR, VAT inclusive.
 * Only used to fill a brand-new database; after that the admin panel is the source of truth.
 * photo is a filename under storage/uploads/, or null when no photo is on file.
 */
export const seedProducts: NewProduct[] = [
  {"category":"Television","category_group":"entertainment","model":"WR32HYHDS","spec":"32\" HD, Frameless, A+ Panel, Android 14, 1GB+8GB, Wall Mount","price":23000,"photo":null},
  {"category":"Television","category_group":"entertainment","model":"WR40HYFHDS","spec":"40\" FHD, Frameless, A+ Panel, Android 14, 1GB+8GB, Wall Mount","price":34490,"photo":null},
  {"category":"Television","category_group":"entertainment","model":"WR43HYFWBS","spec":"43\" FHD, Frameless, A+ Panel, WebOS, Magic Remote, 1GB+8GB, Wall Mount","price":51100,"photo":null},
  {"category":"Television","category_group":"entertainment","model":"WR50HYUWBS","spec":"50\" UHD 4K, Frameless, A+ Panel, WebOS, Magic Remote, 1.5GB+8GB, Wall Mount","price":71990,"photo":null},
  {"category":"Television","category_group":"entertainment","model":"R55UHDP9","spec":"55\" UHD 4K, Frameless, A+ Panel, Android 9.0, 1GB+8GB, Voice Remote, Wall Mount","price":73990,"photo":null},
  {"category":"Television","category_group":"entertainment","model":"WR55HYQWBS","spec":"55\" QLED 4K, Frameless, A+ Panel, WebOS, Magic Remote, 1.5GB+8GB, Wall Mount","price":89990,"photo":null},
  {"category":"Television","category_group":"entertainment","model":"E75A71B","spec":"75\" UHD 4K, Frameless, A+ Panel, Android 9.0, 2GB+16GB, Voice Remote","price":210700,"photo":"e75a71b.jpg"},
  {"category":"Television","category_group":"entertainment","model":"WR65HYQWBS","spec":"65\" QLED 4K, Frameless, A+ Panel, WebOS, Magic Remote, 1.5GB+8GB, Wall Mount","price":135000,"photo":null},
  {"category":"Television","category_group":"entertainment","model":"WR75HYQWBS","spec":"75\" QLED 4K, Frameless, A+ Panel, WebOS, Magic Remote, 1.5GB+8GB, Wall Mount","price":215000,"photo":null},
  {"category":"Multi Door Refrigerator","category_group":"refrigeration","model":"SBSKK525IX","spec":"525 Ltr, Side by Side INOX Door, No Frost, Inverter Compressor, Digital Display","price":110990,"photo":null},
  {"category":"Multi Door Refrigerator","category_group":"refrigeration","model":"SBSKK535GL","spec":"535 Ltr, Side by Side Glass Door, No Frost, Inverter Compressor, Digital Display","price":124990,"photo":null},
  {"category":"Multi Door Refrigerator","category_group":"refrigeration","model":"CDKK500INV","spec":"500 Ltr, Cross Door, Grey Wave Glass, No Frost, Inverter Compressor, Built-In Display","price":129990,"photo":null},
  {"category":"Double Door Refrigerator","category_group":"refrigeration","model":"DDKK265I","spec":"265 Ltr, No Frost, INOX Door, Inverter Compressor, Ice Maker Twister, Glass Shelves","price":62990,"photo":null},
  {"category":"Double Door Refrigerator","category_group":"refrigeration","model":"DDKK325I","spec":"325 Ltr, No Frost, INOX Door, Inverter Compressor, Ice Maker Twister, Glass Shelves","price":74990,"photo":null},
  {"category":"Double Door Refrigerator","category_group":"refrigeration","model":"DDKK365I","spec":"365 Ltr, No Frost, INOX Door, Inverter Compressor, Ice Maker Twister, Glass Shelves","price":81990,"photo":null},
  {"category":"Single Door Refrigerator","category_group":"refrigeration","model":"BC-60","spec":"60 Ltr, PCM Door, Attractive Interior, Large Freezer Compartment, Energy Efficient","price":20990,"photo":"bc60.jpg"},
  {"category":"Single Door Refrigerator","category_group":"refrigeration","model":"SDNC100P","spec":"100 Ltr, PCM Door, Attractive Interior, Large Freezer Compartment, Energy Efficient","price":22190,"photo":null},
  {"category":"Single Door Refrigerator","category_group":"refrigeration","model":"SDNC170P","spec":"170 Ltr, PCM Door, Attractive Interior, Large Freezer, Door Handle, Energy Efficient","price":30690,"photo":null},
  {"category":"Single Door Refrigerator","category_group":"refrigeration","model":"SDNC170V","spec":"170 Ltr, VCM Flower Door, Attractive Interior, Large Freezer, Door Handle, Energy Efficient","price":31990,"photo":null},
  {"category":"Single Door Refrigerator","category_group":"refrigeration","model":"SDNC200V","spec":"200 Ltr, VCM Flower Door, Attractive Interior, Large Freezer, Door Handle, Energy Efficient","price":33490,"photo":null},
  {"category":"Single Door Refrigerator","category_group":"refrigeration","model":"SDNC230V","spec":"230 Ltr, VCM Flower Door, Attractive Interior, Large Freezer, Door Handle, Energy Efficient","price":35990,"photo":null},
  {"category":"Hard Top Freezer","category_group":"refrigeration","model":"HTSS170","spec":"170 Ltr, Hard Top, LED Lamp, Lock & Key, Inner White PCA","price":37390,"photo":null},
  {"category":"Hard Top Freezer","category_group":"refrigeration","model":"HTKK200","spec":"200 Ltr, Hard Top, LED Lamp, Lock & Key, Sliding Glass, 5D Freezing","price":39990,"photo":null},
  {"category":"Hard Top Freezer","category_group":"refrigeration","model":"HTSS250","spec":"250 Ltr, Hard Top, LED Lamp, Lock & Key, Inner White PCA, Sliding Glass","price":49390,"photo":null},
  {"category":"Hard Top Freezer","category_group":"refrigeration","model":"HTSS325","spec":"325 Ltr, Hard Top, LED Lamp, Lock & Key, Inner White PCA, Sliding Glass","price":54990,"photo":null},
  {"category":"Hard Top Freezer","category_group":"refrigeration","model":"HTSS425","spec":"425 Ltr, Hard Top, LED Lamp, Lock & Key, Inner White PCA, Sliding Glass","price":73790,"photo":null},
  {"category":"Hard Top Freezer","category_group":"refrigeration","model":"HTKK400","spec":"400 Ltr, Hard Top, LED Lamp, Lock & Key, Sliding Glass, 5D Freezing","price":71990,"photo":null},
  {"category":"Hard Top Freezer","category_group":"refrigeration","model":"HTKK500","spec":"500 Ltr, Hard Top, LED Lamp, Lock & Key, Sliding Glass, 5D Freezing","price":84990,"photo":null},
  {"category":"Glass Top Freezer","category_group":"refrigeration","model":"EMGT 258","spec":"258 Ltr, Glass Top Curve Design, Lock & Key, Two Basket","price":59990,"photo":"emgt258.jpg"},
  {"category":"Glass Top Freezer","category_group":"refrigeration","model":"EMGT 358","spec":"358 Ltr, Glass Top Curve Design, Lock & Key, Two Basket","price":74990,"photo":"emgt358.jpg"},
  {"category":"Glass Top Freezer","category_group":"refrigeration","model":"EMGT 418","spec":"418 Ltr, Glass Top Curve Design, Lock & Key, Two Basket","price":92490,"photo":"emgt418.jpg"},
  {"category":"Upright / Visi Chiller","category_group":"refrigeration","model":"LC-195","spec":"195 Ltr, Display Chiller, Energy Efficient, Attractive Design, Indoor Light","price":55990,"photo":"lc195.jpg"},
  {"category":"Upright / Visi Chiller","category_group":"refrigeration","model":"LC-220","spec":"220 Ltr, Display Chiller, Energy Efficient, Attractive Design, Indoor Light","price":64690,"photo":"lc220.jpg"},
  {"category":"Upright / Visi Chiller","category_group":"refrigeration","model":"LCSS-315","spec":"315 Ltr, Display Chiller, Energy Efficient, Attractive Design, Indoor Light","price":76490,"photo":"lc315.jpg"},
  {"category":"Upright / Visi Chiller","category_group":"refrigeration","model":"LCSS-425","spec":"425 Ltr, Display Chiller, Energy Efficient, Attractive Design, Indoor Light","price":87450,"photo":null},
  {"category":"Upright / Visi Chiller","category_group":"refrigeration","model":"LC-600","spec":"600 Ltr, Double Door Display Chiller, Energy Efficient, Indoor Light","price":149990,"photo":"lc600.jpg"},
  {"category":"Upright / Visi Chiller","category_group":"refrigeration","model":"LCSS-650","spec":"650 Ltr, Double Door Display Chiller, Energy Efficient, Indoor Light","price":159990,"photo":null},
  {"category":"Air Conditioner","category_group":"cooling","model":"WMFXS12K","spec":"1.0 Ton, 12k BTU, Wall Mount, Fixed Speed, Cooling + Heating","price":60990,"photo":"wallmountac.png"},
  {"category":"Air Conditioner","category_group":"cooling","model":"WMINV12KI","spec":"1.0 Ton, 12k BTU, Wall Mount, DC Inverter, WiFi, Cooling + Heating","price":75490,"photo":"wallmountac.png"},
  {"category":"Air Conditioner","category_group":"cooling","model":"WMFXS18K","spec":"1.5 Ton, 18k BTU, Wall Mount, Fixed Speed, Cooling + Heating","price":85990,"photo":"wallmountac.png"},
  {"category":"Air Conditioner","category_group":"cooling","model":"WMINV18KI","spec":"1.5 Ton, 18k BTU, Wall Mount, DC Inverter, WiFi, Cooling + Heating","price":96990,"photo":"wallmountac.png"},
  {"category":"Air Conditioner","category_group":"cooling","model":"WMFXS24K","spec":"2.0 Ton, 24k BTU, Wall Mount, Fixed Speed, Cooling + Heating","price":114990,"photo":"wallmountac.png"},
  {"category":"Air Conditioner","category_group":"cooling","model":"WMINV24KI","spec":"2.0 Ton, 24k BTU, Wall Mount, DC Inverter, WiFi, Cooling + Heating","price":134990,"photo":"wallmountac.png"},
  {"category":"Air Cooler","category_group":"cooling","model":"Personal","spec":"Bliss 35 Ltr, Honeycomb Filter, Energy Efficient, Attractive Design","price":11990,"photo":"personalcooler.jpg"},
  {"category":"Air Cooler","category_group":"cooling","model":"Tower","spec":"Ice Chill 50 Ltr, Honeycomb Filter, Energy Efficient, Attractive Design","price":12990,"photo":"towercooler.jpg"},
  {"category":"Air Cooler","category_group":"cooling","model":"Tower","spec":"Carnival 65 Ltr, Honeycomb Filter, Energy Efficient, Attractive Design","price":18990,"photo":"towercooler.jpg"},
  {"category":"Air Cooler","category_group":"cooling","model":"Desert","spec":"Supreme 75 Ltr, Honeycomb Filter, Energy Efficient, Attractive Design","price":18590,"photo":"desertcooler.jpg"},
  {"category":"Air Cooler","category_group":"cooling","model":"Desert","spec":"Brezza 90 Ltr, Honeycomb Filter, Energy Efficient, Attractive Design","price":19990,"photo":"desertcooler.jpg"},
  {"category":"Washing Machine (Front Loading)","category_group":"laundry","model":"FLXQG70","spec":"7 KG, Automatic, 1200RPM, Universal Motor","price":49990,"photo":"flxqg70.jpg"},
  {"category":"Washing Machine (Front Loading)","category_group":"laundry","model":"FLWLG07UNI","spec":"7 KG, Automatic, 1200RPM, Universal Motor","price":51990,"photo":null},
  {"category":"Washing Machine (Front Loading)","category_group":"laundry","model":"FLWLG08INV","spec":"8 KG, Automatic, 1400RPM, Energy Efficient, BLDC Motor","price":64990,"photo":null},
  {"category":"Washing Machine (Front Loading)","category_group":"laundry","model":"FLXQG08IN","spec":"8 KG, Automatic, 1400RPM, Energy Efficient, BLDC Motor","price":65950,"photo":"flxqg08inv.jpg"},
  {"category":"Washing Machine (Front Loading)","category_group":"laundry","model":"FLWLG10INV","spec":"10 KG, Automatic, 1400RPM, Energy Efficient, BLDC Motor, Touch Panel","price":81990,"photo":null},
  {"category":"Washing Machine (Front Loading)","category_group":"laundry","model":"FLWLGXINVT","spec":"10 KG, Automatic, 1400RPM, Energy Efficient, BLDC Motor, Full Glass Touch Panel","price":89990,"photo":null},
  {"category":"Dishwasher","category_group":"kitchen","model":"WDW7635G","spec":"Futuristic Design, 13 Place Setting, Free Standing, 6 Programmes, LED Light","price":75990,"photo":"wdw7635g.jpg"},
  {"category":"Dishwasher","category_group":"kitchen","model":"WDW7609Q","spec":"Futuristic Design, 15 Place Setting, Free Standing, 7 Programmes, LED Screen","price":86490,"photo":"wdw7609q.jpg"},
  {"category":"Microwave Oven","category_group":"kitchen","model":"WBMW25GR002","spec":"Stylish, 25 Ltr, Combi Hybrid Oven, Automated Menu","price":20190,"photo":"wbmw25gr002.png"},
  {"category":"Microwave Oven","category_group":"kitchen","model":"WBMW25CV001","spec":"Stylish, 25 Ltr, Convection Oven, Automated Menu","price":22190,"photo":"wbmw25cv001.png"},
  {"category":"OTG","category_group":"kitchen","model":"WBOTG20L","spec":"Stylish, 20 Ltr, 60Min Timer with Bell, High Quality Stainless Steel","price":8390,"photo":"wbotg20l.jpg"},
  {"category":"OTG","category_group":"kitchen","model":"WBOTG25L","spec":"Stylish, 25 Ltr, 60Min Timer with Bell, High Quality Stainless Steel","price":9190,"photo":"wbotg25l.jpg"},
  {"category":"OTG","category_group":"kitchen","model":"WBOTG33L","spec":"Stylish, 35 Ltr, 60Min Timer with Bell, High Quality Stainless Steel","price":10590,"photo":"wbotg35l.jpg"},
  {"category":"Gas Cooktop","category_group":"kitchen","model":"WBGS2050A","spec":"Steel, 2 Burner Cooktop, Attractive Design, Auto Ignition, Silver Color","price":3490,"photo":"wbgs050a.jpg"},
  {"category":"Gas Cooktop","category_group":"kitchen","model":"WBGS2050B","spec":"Steel, 2 Burner Cooktop, Attractive Design, Auto Ignition, Black Color","price":3490,"photo":"wbgs2050b.png"},
  {"category":"Gas Cooktop","category_group":"kitchen","model":"WBGSB4001","spec":"Glass, 4 Burner Cooktop, Attractive Design, Toughened Glass","price":12190,"photo":"wbgsb4001.jpg"},
  {"category":"Infrared Cooktop","category_group":"kitchen","model":"WBIRDP01","spec":"Double Pan, Handle, Energy Efficient, Timer, Multi Cook Function","price":12190,"photo":"wbirdpo1.jpg"},
  {"category":"Rice Cooker","category_group":"kitchen","model":"WBRC15DM","spec":"1.5 Ltr, Delux, Warmer, Energy Efficient, Attractive Design","price":3250,"photo":"wbrc15dm.jpg"},
  {"category":"Rice Cooker","category_group":"kitchen","model":"WBRC15DRM","spec":"1.5 Ltr, Drum, Warmer, Energy Efficient, Attractive Design","price":3190,"photo":null},
  {"category":"Rice Cooker","category_group":"kitchen","model":"WBRC18DM","spec":"1.8 Ltr, Delux, Warmer, Energy Efficient, Attractive Design","price":3450,"photo":"wbrc18dm.jpg"},
  {"category":"Rice Cooker","category_group":"kitchen","model":"WBRC18DRM","spec":"1.8 Ltr, Drum, Warmer, Energy Efficient, Attractive Design","price":3550,"photo":null},
  {"category":"Rice Cooker","category_group":"kitchen","model":"WBRC22DM","spec":"2.2 Ltr, Delux, Warmer, Energy Efficient, Attractive Design","price":3750,"photo":"wbrc22dm.jpg"},
  {"category":"Rice Cooker","category_group":"kitchen","model":"WBRC22DRM","spec":"2.2 Ltr, Drum, Warmer, Energy Efficient, Attractive Design","price":3650,"photo":null},
  {"category":"Rice Cooker","category_group":"kitchen","model":"WBRC28DM","spec":"2.8 Ltr, Delux, Warmer, Energy Efficient, Attractive Design","price":4095,"photo":null},
  {"category":"Mixture Grinder","category_group":"kitchen","model":"KIS2JD","spec":"Glossy, Attractive, 500 Watt Powerful Motor, 2 Jar Set","price":3200,"photo":null},
  {"category":"Mixture Grinder","category_group":"kitchen","model":"KIS3IM","spec":"Glossy, Attractive, 500 Watt Powerful Motor, 3 Jar Set","price":3590,"photo":null},
  {"category":"Mixture Grinder","category_group":"kitchen","model":"KIS3JP","spec":"Glossy, Attractive, 500 Watt Powerful Motor, 3 Jar Set","price":3690,"photo":"kis3jp.png"},
  {"category":"Air Fryer","category_group":"kitchen","model":"WBAF4204M","spec":"Stylish Design, Energy Efficient, 4 Ltr, Manual","price":7990,"photo":null},
  {"category":"Air Fryer","category_group":"kitchen","model":"WBAF4204D","spec":"Stylish Design, Energy Efficient, 4 Ltr, Digital","price":8990,"photo":null},
  {"category":"Electric Kettle","category_group":"kitchen","model":"WB-EK8811","spec":"Stylish Design, 1.8L, Energy Efficient, Food Grade Steel, Auto On/Off","price":1295,"photo":null},
  {"category":"Electric Kettle","category_group":"kitchen","model":"WB-EK188","spec":"Stylish Design, 1.8L, Energy Efficient, Food Grade Steel, Auto On/Off","price":1450,"photo":null},
  {"category":"Electric Kettle","category_group":"kitchen","model":"WB-EK18E","spec":"Stylish Design, 1.8L, Energy Efficient, Food Grade Steel, Auto On/Off","price":1650,"photo":null},
  {"category":"Water Geyser","category_group":"home","model":"PLATINUM G15","spec":"Futuristic Look, SS 304 Tank, Copper Element, ABS Body, 15 Ltr","price":12690,"photo":null},
  {"category":"Water Geyser","category_group":"home","model":"SUNSHINE G15","spec":"Futuristic Look, SS 304 Tank, Copper Element, ABS Body, 15 Ltr","price":12690,"photo":null},
  {"category":"Water Geyser","category_group":"home","model":"PLATINUM G25","spec":"Futuristic Look, SS 304 Tank, Copper Element, ABS Body, 25 Ltr","price":15990,"photo":null},
  {"category":"Water Geyser","category_group":"home","model":"SUNSHINE G25","spec":"Futuristic Look, SS 304 Tank, Copper Element, ABS Body, 25 Ltr","price":15990,"photo":null},
  {"category":"Water Dispenser","category_group":"home","model":"WBWD1004T","spec":"Stylish Design, Energy Efficient, Hot/Cold/Normal Water, Table Top","price":9390,"photo":null},
  {"category":"Water Dispenser","category_group":"home","model":"WBWD1004S","spec":"Stylish Design, Energy Efficient, Hot/Cold/Normal Water, Tower","price":10990,"photo":null},
  {"category":"Water Dispenser","category_group":"home","model":"WBWD1008S","spec":"Stylish Design, Energy Efficient, Hot/Cold/Normal Water, Tower","price":11490,"photo":null},
  {"category":"Ceiling Fan","category_group":"home","model":"FAN 24\"","spec":"24\", Attractive Design, Energy Efficient","price":2790,"photo":"fan24.jpg"},
  {"category":"Ceiling Fan","category_group":"home","model":"FAN 36\"","spec":"36\", Attractive Design, Energy Efficient","price":2850,"photo":"fan36.jpg"},
  {"category":"Ceiling Fan","category_group":"home","model":"FAN 48\"","spec":"48\", Attractive Design, Energy Efficient","price":2990,"photo":"fan48.jpg"},
  {"category":"Stand Fan","category_group":"home","model":"WBSF-16-6301","spec":"16\", Attractive Design, Five Blade, Strong Base","price":3990,"photo":"wbsf166301.jpg"},
  {"category":"Stand Fan","category_group":"home","model":"WBSF-18-LF","spec":"18\", Attractive Design, Five Blade, Strong Base","price":4390,"photo":null},
  {"category":"Stand Fan","category_group":"home","model":"WBSF-18-GFR","spec":"18\", Attractive Design, Five Blade, Strong Base, Remote","price":5990,"photo":null},
  {"category":"Iron","category_group":"home","model":"CEI-DI-15","spec":"Attractive Design, 1000 Watt, Non-Stick, SOLE Plate, Powerful","price":995,"photo":null},
  {"category":"Iron","category_group":"home","model":"CEI-DI-07","spec":"Attractive Design, 1000 Watt, Non-Stick, SOLE Plate, Powerful","price":1095,"photo":null},
  {"category":"Iron","category_group":"home","model":"CEI-DI-08","spec":"Attractive Design, 1000 Watt, Non-Stick, SOLE Plate, Powerful","price":1095,"photo":null},
  {"category":"Iron","category_group":"home","model":"WBDIDSW-3","spec":"Attractive Design, 1000 Watt, Non-Stick, SOLE Plate, Powerful","price":1450,"photo":null},
  {"category":"Iron","category_group":"home","model":"WBDIDSW-5","spec":"Attractive Design, 1000 Watt, Non-Stick, SOLE Plate, Powerful","price":1490,"photo":null},
  {"category":"Iron","category_group":"home","model":"WBDIDSW-8","spec":"Attractive Design, 1000 Watt, Non-Stick, SOLE Plate, Powerful","price":1590,"photo":null},
  {"category":"Iron","category_group":"home","model":"WBSISW-106","spec":"Steam, Attractive Design, 1250 Watt, Non-Stick, SOLE Plate, Powerful","price":1790,"photo":null},
  {"category":"Iron","category_group":"home","model":"WBSISW-618","spec":"Steam, Attractive Design, 2000 Watt, Non-Stick, SOLE Plate, Powerful","price":2650,"photo":null},
];
